- name: Checkout gh-pages branch
  run: git checkout gh-pages

- name: Copy Resume.pdf to root of gh-pages branch
  run: cp Resume.pdf .

- name: Add Resume.pdf to git index
  run: git add Resume.pdf

- name: Commit changes to gh-pages branch
  run: git commit -m "Add Resume.pdf to gh-pages branch"

- name: Push changes to gh-pages branch
  run: git push origin gh-pages
